package assets

import "github.com/glmaljkovich/lettertracer/assets/audio/letters"

// Letters image paths
var Letters = []string{
	"./assets/img/a.png",
	"./assets/img/b.png",
	"./assets/img/c.png",
	"./assets/img/d.png",
	"./assets/img/e.png",
	"./assets/img/f.png",
	"./assets/img/g.png",
	"./assets/img/h.png",
	"./assets/img/i.png",
	"./assets/img/j.png",
	"./assets/img/k.png",
	"./assets/img/l.png",
	"./assets/img/m.png",
	"./assets/img/n.png",
	"./assets/img/o.png",
	"./assets/img/p.png",
	"./assets/img/q.png",
	"./assets/img/r.png",
	"./assets/img/s.png",
	"./assets/img/t.png",
	"./assets/img/u.png",
	"./assets/img/v.png",
	"./assets/img/w.png",
	"./assets/img/x.png",
	"./assets/img/y.png",
	"./assets/img/z.png",
}

// SoundFiles mp3 paths
var SoundFiles = [][]byte{
	letters.A,
	letters.B,
	letters.C,
	letters.D,
	letters.E,
	letters.F,
	letters.G,
	letters.H,
	letters.I,
	letters.J,
	letters.K,
	letters.L,
	letters.M,
	letters.N,
	letters.O,
	letters.P,
	letters.Q,
	letters.R,
	letters.S,
	letters.T,
	letters.U,
	letters.V,
	letters.W,
	letters.X,
	letters.Y,
	letters.Z,
	// "./assets/audio/letters/a.mp3",
	// "./assets/audio/letters/b.mp3",
	// "./assets/audio/letters/c.mp3",
	// "./assets/audio/letters/d.mp3",
	// "./assets/audio/letters/e.mp3",
	// "./assets/audio/letters/f.mp3",
	// "./assets/audio/letters/g.mp3",
	// "./assets/audio/letters/h.mp3",
	// "./assets/audio/letters/i.mp3",
	// "./assets/audio/letters/j.mp3",
	// "./assets/audio/letters/k.mp3",
	// "./assets/audio/letters/l.mp3",
	// "./assets/audio/letters/m.mp3",
	// "./assets/audio/letters/n.mp3",
	// "./assets/audio/letters/o.mp3",
	// "./assets/audio/letters/p.mp3",
	// "./assets/audio/letters/q.mp3",
	// "./assets/audio/letters/r.mp3",
	// "./assets/audio/letters/s.mp3",
	// "./assets/audio/letters/t.mp3",
	// "./assets/audio/letters/u.mp3",
	// "./assets/audio/letters/v.mp3",
	// "./assets/audio/letters/w.mp3",
	// "./assets/audio/letters/x.mp3",
	// "./assets/audio/letters/y.mp3",
	// "./assets/audio/letters/z.mp3",
}
